export { analyzeTrend } from './trend-analyzer.js'
export type { TrendAnalysis } from './trend-analyzer.js'
export { generateIdeas } from './idea-generator.js'
export type { ContentIdea } from './idea-generator.js'
export { writeScript } from './scriptwriter.js'
export type { ContentScript } from './scriptwriter.js'
export { checkBrand } from './brand-checker.js'
export type { BrandCheckResult } from './brand-checker.js'
export { generateVariants, generateCoverVariants } from './variant-generator.js'
export type { ScriptVariant, CoverConcept } from './variant-generator.js'
export { convertFormat } from './format-converter.js'
export type { ConvertedScript } from './format-converter.js'
// NOTE: music-suggester and viral-analyzer below are implemented but not yet wired into any
// route/worker (features, not duplicates) — kept intentionally. The former cover-concept and
// storyboard agents were removed (superseded by variant-generator and video-storyboard).
export { suggestMusic } from './music-suggester.js'
export type { MusicSuggestion } from './music-suggester.js'
export { planSeries } from './series-planner.js'
export type { SeriesEpisode } from './series-planner.js'
export { getRecommendations } from './recommender.js'
export { generateVideoStoryboard } from './video-storyboard.js'
export type { VideoShot } from './video-storyboard.js'
export { analyzeViralVideo } from './viral-analyzer.js'
export type { ViralInsight } from './viral-analyzer.js'
export { analyzeCompany } from './company-portrait-analyzer.js'
export type { CompanyInput, CompanyPortraitResult } from './company-portrait-analyzer.js'
export { generateContentPlan } from './content-plan-generator.js'
export type { ContentPlanRequest, ContentPlanItemDraft } from './content-plan-generator.js'
export { runSalesAgent } from './sales-agent.js'
export type { SalesAgentResult, SalesQualification } from './sales-agent.js'
